# .gitconfig_local.inc
[user]
	#email = kumarstack55@gmail.com
	#name = kumarstack55
[core]
	#editor = vim -c \"set fenc=utf-8\"
	#editor = gvim -c \"set fenc=utf-8\"
	#editor = nvim -c \"set fenc=utf-8\"

	# git diff の tab サイズを 4 にする。
	#pager = less -x4

	# commit 時に CRLF を LF に変換する。
	# https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration
	#autocrlf = false
[http]
	#proxy = http://proxy.example.com:8080
	#sslVerify = false
[https]
	#proxy = http://proxy.example.com:8080
