name: CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Configure git to prevent warnings from being raised in checkout
      run: |
        git config --global advice.detachedHead false

    - uses: actions/checkout@v1

    - name: Output information about the test environment
      run: |
        set -x
        exec 1>&2
        uname -n
        whoami
        echo $SHELL
        type bash
        bash --version
        pwd
        ls
        type tmux
        type vi
        type vim
        type nvim || true
        type python
        python --version

    - name: Install nvim
      run: |
        set -x
        exec 1>&2
        sudo apt-get install neovim

    - name: Install the dotfiles
      run: |
        set -x
        exec 1>&2
        cd ./bin
        ./installer.sh

    - name: Install the nvim plugins
      run: |
        set -x
        exec 1>&2
        nvim -u "~/.config/nvim/plugins.vim" \
          -c "try | PlugInstall --sync | finally | qall! | endtry"

    - name: Test
      run: |
        set -x
        exec 1>&2
        pwd
        type python
        python --version
        ./tests/nvim_ultisnips.sh
