name: CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Configure git to prevent warnings from being raised in checkout
      run: |
        git config --global advice.detachedHead false

    - uses: actions/checkout@v1

    - name: Output information about the test environment
      run: |
        set -x
        exec 1>&2
        uname -n
        whoami
        echo $SHELL
        type bash
        bash --version
        pwd
        ls
        type tmux
        type vi
        type vim
        type nvim || true
        type python
        python --version
        type ansible
        ansible --version

    - name: Install nvim
      run: |
        set -x
        exec 1>&2
        sudo apt-get install neovim
        nvim --version

    - name: Install ansible 2.5
      run: |
        set -x
        exec 1>&2
        sudo apt update
        sudo apt install software-properties-common
        sudo apt-add-repository --yes --update \
          ppa:ansible/ansible
        sudo apt-cache showpkg ansible
        sudo apt-get remove ansible
        sudo apt install ansible=2.5.1+dfsg-1ubuntu0.1
        ansible --version

    - name: Install the dotfiles
      run: |
        set -x
        exec 1>&2
        cd ./bin
        ./installer.sh

    - name: Install the nvim plugins
      run: |
        set -x
        exec 1>&2
        nvim -u "~/.config/nvim/plugins.vim" \
          -c "try | PlugInstall --sync | finally | qall! | endtry"

    - name: Run tests
      run: |
        set -x
        exec 1>&2
        pwd
        type python
        python --version
        ./tests/run.sh
