name: CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Configure git to prevent warnings from being raised in checkout
      run: |
        git config --global advice.detachedHead false

    - uses: actions/checkout@v1

    - name: Output information about the test environment
      run: |
        set -x
        exec 1>&2
        uname -n
        whoami
        echo $SHELL
        type bash
        bash --version
        echo $TERM
        pwd
        ls
        type tmux
        type vi
        type vim
        type nvim || true
        type python
        python --version
        type ansible
        ansible --version

    - name: Output apt list
      run: |
        set -x
        apt list >apt_list-$(date '+%F').txt

    - name: Upload apt list result
      uses: actions/upload-artifact@v1
      with:
        name: homework
        path: apt_list-$(date '+%F').txt

    - name: Install nvim
      run: |
        set -x
        exec 1>&2
        sudo apt install neovim
        nvim --version

    - name: Install pynvim
      run: |
        set -x
        exec 1>&2
        python2 -m pip install --user --upgrade pynvim

    - name: Install ansible 2.5
      run: |
        set -x
        exec 1>&2
        sudo apt update
        sudo apt install software-properties-common
        sudo apt-add-repository --yes --update \
          ppa:ansible/ansible
        sudo apt-cache showpkg ansible
        sudo apt-get remove ansible
        sudo apt install ansible=2.5.1+dfsg-1ubuntu0.1
        ansible --version

    - name: Install the dotfiles
      run: |
        set -x
        exec 1>&2
        cd ./bin
        sudo apt install python3-setuptools
        sudo apt install python3-wheel
        ./installer.sh

    - name: Check the nvim health
      run: |
        set -x
        exec 1>&2
        nvim -c "checkhealth | w! /tmp/checkhealth.txt | qall!"
        cat /tmp/checkhealth.txt

    - name: Run tests
      run: |
        set -x
        exec 1>&2
        pwd
        type python
        python --version
        ./tests/run.sh
