name: CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Configure git to prevent warnings from being raised in checkout
      run: |
        git config --global advice.detachedHead false

    - uses: actions/checkout@v1

    - name: Run a multi-line script
      run: |
        set -x
        uname -n
        whoami
        pwd
        ls
        type bash
        bash --version
        type tmux
        type vi
        type vim
        sudo apt-get install neovim
        type nvim
        cd ./bin
        type python
        python --version
        ./installer.sh
        nvim -u "~/.config/nvim/plugins.vim" -c "try | PlugInstall | finally | qall! | endtry"
