name: CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Configure git to prevent warnings from being raised in checkout
      run: |
        git config --global advice.detachedHead false

    - uses: actions/checkout@v1

    - name: Output information about the test environment
      run: |
        set -x
        exec 1>&2
        uname -n
        whoami
        echo $SHELL
        type bash
        bash --version
        echo "TERM: $TERM"
        pwd
        ls
        type tmux
        type vi
        type vim
        type nvim || true
        type python
        python --version
        type ansible
        ansible --version

    - name: Output apt list
      run: |
        set -x
        apt list >apt_list.txt

    - name: Upload apt list result
      uses: actions/upload-artifact@v1
      with:
        name: apt_list.txt
        path: apt_list.txt

    - name: Install nvim
      run: |
        set -x
        exec 1>&2
        sudo apt install neovim
        nvim --version

    - name: Install the dotfiles
      run: |
        set -x
        exec 1>&2
        cd ./bin
        sudo apt install python3-setuptools
        sudo apt install python3-wheel
        ./installer.sh

    - name: Check the nvim health
      run: |
        set -x
        exec 1>&2
        nvim -c "checkhealth | w! /tmp/checkhealth.txt | qall!"
        cat /tmp/checkhealth.txt
