name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Run a multi-line script
      run: |
        uname -n
        pwd
        ls
        type bash
        bash --version
        type tmux
        type vi
        type vim
        type nvim
        cd $HOME/dotfiles/bin
        ./installer.sh
